apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-r5di
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ueqe-tenant/rhtap-demo-app/hacbs-test-project-r5di@sha256:82ae8e7cd8fccd2aeee06aa4f8d58c61a712e153144bb2501f105f1d379fa8a3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
