apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-r5di
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-r5di
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-r5di
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-r5di
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-r5di
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ueqe-tenant/rhtap-demo-app/hacbs-test-project-r5di@sha256:82ae8e7cd8fccd2aeee06aa4f8d58c61a712e153144bb2501f105f1d379fa8a3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
